=== haizicq/osframe/framework/src/main/java/com/os/osframe/frame/scaffold/dataInfo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.example.org/dataInfo"
		elementFormDefault="qualified">

	<simpleType name="class">
		<annotation>
			<documentation>Java类</documentation>
		</annotation>
		<restriction base="string"></restriction>
	</simpleType>
  	<element name="tables">
		<annotation>
			<documentation>模型表信息列表</documentation>
		</annotation>
		<complexType>
			<sequence>
				<element
					name="table" maxOccurs="unbounded" minOccurs="1">
					<annotation>
						<documentation>模型表信息</documentation>
					</annotation>
					<complexType>
						<sequence>
								<element name="fields" maxOccurs="1" minOccurs="1">
									<annotation>
										<documentation>
											字段列表
										</documentation>
									</annotation>
									<complexType>
										<sequence maxOccurs="unbounded" minOccurs="1">
											<element name="field">
												<annotation>
													<documentation>
														字段信息
													</documentation>
												</annotation>
												<complexType>
													<attribute
														name="id"
														use="required">
														<annotation>
															<documentation>
																表字段
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="name"
														use="required">
														<annotation>
															<documentation>
																表字段描述
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="type">
														<annotation>
															<documentation>
																字段数据库类型
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="length">
														<annotation>
															<documentation>
																字段长度
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="javaType">
														<annotation>
															<documentation>
																字段Java代码类型
															</documentation>
														</annotation>
													</attribute>
													<attribute
															name="mapping">
														<annotation>
															<documentation>
																映射关系，OneToMany 一对多，ManyToMany 多对多
															</documentation>
														</annotation>
													</attribute>

													<attribute
														name="required"
														type="boolean">
														<annotation>
															<documentation>
																字段是否必填
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="foreignId">
														<annotation>
															<documentation>
																外键类型Id字段
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="foreignName">
														<annotation>
															<documentation>
																外键类型名称字段
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="selectType">
														<annotation>
															<documentation>
																选择类型，可以为下拉框、单选按钮、复选框等
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="dataSource">
														<annotation>
															<documentation>
																复选类型的数据来源，可为枚举、数据库
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="enums">
														<annotation>
															<documentation>
																枚举类型，枚举键值用冒号隔开，多个值用下划线隔开，如：key1:value1|key2:value2
															</documentation>
														</annotation>
													</attribute>
													<attribute
														name="remark">
														<annotation>
															<documentation>
																备注
															</documentation>
														</annotation>
													</attribute>
													<attribute
															name="joinTable">
														<annotation>
															<documentation>
																多对多级联的表名
															</documentation>
														</annotation>
													</attribute>
													<attribute
															name="joinSourceField">
														<annotation>
															<documentation>
																级联源字段
															</documentation>
														</annotation>
													</attribute>
													<attribute
															name="joinTargetField">
														<annotation>
															<documentation>
																级联目标字段
															</documentation>
														</annotation>
													</attribute>
												</complexType>
											</element>
										</sequence>
									</complexType>
								</element>
								
						</sequence>
								<attribute
									name="name"
									type="string"
									use="required">
									<annotation>
										<documentation>
											表名
										</documentation>
									</annotation>
								</attribute>
								<attribute
									name="info"
									type="string"
									use="required">
									<annotation>
										<documentation>
											表描述
										</documentation>
									</annotation>
								</attribute>
								<attribute
									name="status"
									type="boolean">
									<annotation>
										<documentation>
											是否允许重新生成表
										</documentation>
									</annotation>
								</attribute>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>										
</schema>

=== haizicq/osframe/demo/src/main/resources/com/os/osframe/os/demo/dataInfo/os_demo_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables
	xmlns="http://www.example.org/dataInfo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dataInfo  http://www.example.org/dataInfo/xml/dataInfo.xsd">
	<!--
	    样例模块
	    展示内容包括：一个简单的增删改查功能、基础标签使用（对话框/时间/枚举等）、权限
	    表设计
	    os_demo_info
	    字段：名称、类型、上级、所属组织、测试时间
	    添加功能：url权限拦截、数据过滤
	  -->

	<table name="os_demo_info" info="测试信息" status="true">
		<fields>
			<field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
			<field name="类型" id="lb_type" javaType="String" type="varchar" length="2"/>
			<field name="测试时间" id="lb_time" javaType="Date" />
			<field
					id="lb_parent"
					name="上级"
					javaType="com.bladeray.softdp.os.demo.domain.OsDemoInfo"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
			<field
					id="lb_dept"
					name="所属组织"
					javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
		</fields>
	</table>

</tables>

=== haizicq/osframe/users/src/main/resources/com/os/osframe/core/users/dataInfo/msc_users_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables
	xmlns="http://www.example.org/dataInfo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dataInfo  http://www.example.org/dataInfo/xml/dataInfo.xsd">
	<!--
	    表：
	    基础表：主键、类型(人/组织/部门/岗位/群类)、层级Id、上级ID、关键字、编码、名称、备注、是否虚拟、是否有效、排序号、集成源关键字、集成主键、创建时间、修改时间
	    人员信息表：主键、基础表ID、登陆名、密码、邮箱、电话、手机、其他通讯方式、默认语言
	    部门组织表：主键、基础表ID、部门领导、
	    岗位信息表：主键、基础表ID、岗位级别(由小到大，越小越大)、岗位类型(用于标注平行类岗位在不同部门中时，如部门的考勤员和财务人员)、岗位成员

	    岗位类型表：主键、名称、编码、级别、关键字、备注（包括：总经理、副总、经理、副经理、主任、组长、考勤员、财务员等）

        群组类型表：主键、名称、编码、关键字、备注（包括：一般群组、项目组、）

	    群组组织表：主键、基础表ID、群组类型、群组领导
	    群组岗位表：主键、基础表ID、岗位级别、岗位成员

        //后续单独模块实现，这里组织设计可以达到支撑即可
        集团分级授权：集团作为根级组织，底下挂各分子公司，业务模块设置时需要分别设置集团管理员以及各分子公司管理员，一般集团管理员由系统管理员设置，
        而分子公司管理员由集团管理员设置，也可以由系统管理员设置

	  -->

    <table name="msc_users_info" info="组织基础信息" status="true">
		<fields>
			<field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
			<field name="关键字" id="lb_key" javaType="String" type="varchar" length="200"/>
            <field name="类型" id="lb_type" javaType="String" type="varchar" length="200"/>
            <field name="编码" id="lb_no" javaType="String" type="varchar" length="200"/>
            <field name="排序号" id="lb_order" javaType="Integer" />
            <field name="层级" id="lb_levels_id"  javaType="String" type="CLOB" length="2000"/>
            <field name="是否虚拟" id="lb_is_virtual" javaType="String" type="varchar" length="10"/>
            <field name="是否有效" id="lb_is_valid" javaType="String" type="varchar" length="10"/>
            <field name="备注" id="lb_info" javaType="String" type="varchar" length="255"/>
            <field name="创建时间" id="lb_create_time" javaType="Date" type="date"/>
            <field name="修改时间" id="lb_update_time" javaType="Date" type="date"/>
            <field name="集成源关键字" id="lb_source_key" javaType="String" type="varchar" length="200"/>
            <field name="集成主键" id="lb_source_pk" javaType="String" type="varchar" length="200"/>
            <field
                    id="lb_parent"
                    name="上级组织"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
        </fields>
	</table>
    <table name="msc_users_org" info="部门组织" status="true">
        <fields>
            <field
                    id="lb_users_info"
                    name="基础信息"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <field
                    id="lb_leader"
                    name="部门领导"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
        </fields>
    </table>

    <table name="msc_users_person" info="人员信息" status="true">
        <fields>
            <field name="登录名" id="lb_login_name" javaType="String" type="varchar" length="200"/>
            <field name="密码" id="lb_pwd" javaType="String" type="varchar" length="200"/>
            <field name="邮箱" id="lb_mail" javaType="String" type="varchar" length="200"/>
            <field name="电话" id="lb_phone" javaType="String" type="varchar" length="200"/>
            <field name="手机" id="lb_mobile_phone" javaType="String" type="varchar" length="200"/>
            <field name="其他通讯" id="lb_others" javaType="String" type="varchar" length="255"/>
            <field name="默认语言" id="lb_language" javaType="String" type="varchar" length="10"/>
            <field
                    id="lb_users_info"
                    name="基础信息"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
        </fields>
    </table>
    <!-- 岗位信息表：主键、基础表ID、岗位级别(由小到大，越小越大，为空则为最小)、岗位类型(用于标注平行类岗位在不同部门中时，如部门的考勤员和财务人员)、岗位成员 -->
    <table name="msc_users_job" info="岗位信息" status="true">
        <fields>
            <field name="级别" id="lb_level" javaType="String" type="varchar" length="200"/>

            <field
                    id="lb_job_type"
                    name="岗位类型"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersJobType"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <field
                    id="lb_users_info"
                    name="基础信息"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <field
                    id="lb_person_list"
                    name="成员列表"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    mapping="ManyToMany"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>

        </fields>
    </table>
    <!-- 主键、名称、编码、级别、关键字、备注（包括：总经理、副总、经理、副经理、主任、组长、考勤员、财务员等）-->
    <table name="msc_users_job_type" info="岗位类型" status="true">
        <fields>
            <field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
            <field name="编码" id="lb_no" javaType="String" type="varchar" length="200"/>
            <field name="级别" id="lb_level" javaType="String" type="varchar" length="200"/>
            <field name="关键字" id="lb_key" javaType="String" type="varchar" length="200"/>
            <field name="备注" id="lb_info" javaType="String" type="varchar" length="200"/>
            <field name="状态" id="lb_status" javaType="String" type="varchar" length="20"/>
            <field name="更新时间" id="lb_update_time" javaType="Date" />
        </fields>
    </table>



    <!-- 群组类型表：主键、名称、编码、关键字、备注（包括：简单群组、项目组、）-->
    <table name="msc_users_group_type" info="群组类型" status="true">
        <fields>
            <field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
            <field name="编码" id="lb_no" javaType="String" type="varchar" length="200"/>
            <field name="关键字" id="lb_key" javaType="String" type="varchar" length="200"/>
            <field name="备注" id="lb_info" javaType="String" type="varchar" length="200"/>
            <field name="状态" id="lb_status" javaType="String" type="varchar" length="20"/>
            <field name="更新时间" id="lb_update_time" javaType="Date" />
        </fields>
    </table>


    <!-- 群组组织表：主键、基础表ID、群组类型、群组领导-->
    <table name="msc_users_group" info="群组组织" status="true">
        <fields>
            <field
                    id="lb_leader"
                    name="群组领导"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <field
                    id="lb_group_type"
                    name="群组类型"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersGroupType"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <field
                    id="lb_users_info"
                    name="基础信息"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <!-- 群组成员：简单群组情况 -->
            <field
                    id="lb_person_list"
                    name="成员列表"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    mapping="ManyToMany"
                    joinTable="msc_users_group_persons"
                    joinSourceField="lb_group_id"
                    joinTargetField="lb_person_id"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
        </fields>
    </table>

    <!-- 群组岗位表：主键、基础表ID、岗位级别、岗位成员-->
    <table name="msc_users_group_job" info="群组岗位类型" status="true">
        <fields>
            <field name="岗位级别" id="lb_level" javaType="String" type="varchar" length="200"/>
            <field
                    id="lb_users_info"
                    name="基础信息"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
            <field
                    id="lb_person_list"
                    name="成员列表"
                    javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
                    mapping="ManyToMany"
                    foreignId="pkId"
                    foreignName="lbName"
                    selectType="select"
                    dataSource="database"/>
        </fields>
    </table>
</tables>

=== haizicq/osframe/auth/src/main/resources/com/os/osframe/core/auth/dataInfo/msc_auth_info.xml
<?xml version="1.0" encoding="UTF-8"?>
<tables
	xmlns="http://www.example.org/dataInfo"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/dataInfo  http://www.example.org/dataInfo/xml/dataInfo.xsd">
	<!--
	    权限设计，角色和链接权限在xml中定义，然后写入到表中供调用。
	    包含表：角色分组、角色表（角色授权表）、权限表、url链接、数据权限表

	    角色分组表：ID、名称、备注、关键字、排序号
	    角色表：ID 、名称、关键字、角色类型(管理员(所有权限)/开发者(所有权限、弹出调试日志)/匿名(可定制部分权限)、自定义权限/集团管理员)、上级角色、有效性、所属分组
	    权限表：ID、名称、国际化名称、描述、角色key、控制路径前缀、所属模块、所属系统、导入时间
	    角色授权（角色表的多对多字段）：角色ID 、权限ID
	    角色成员（角色表的多对多字段）

	    数据权限记录表：ID 、模块ID 、模块包路径、数据类型(阅读者／编辑者／下载者)、为空处理(所有人有权限/所有人无权限)、人员查看列表、人员解析列表

	    设计思路，权限不与菜单绑定，而直接在项目中通过配置将链接的权限属性配置进去，
	    权限校验可以直接按角色校验，也可以按自定义的权限类型校验

        数据权限过滤设计，模块需要关联数据权限时，只需要在保存的时候调用权限数据保存将数据保存到这张表来，
        解析时直接高年级模块包路径和id来查到记录，然后将查询数据直接过滤出来，或者提示权限不足
        数据过滤调用url直接进入时，在进入之前根据url判断模块，然后根据配置的id规则判断模块主键，然后直接拦截

	  	功能设计：权限导入(提供xml配置)、数据信息要由模块保存数据时写入、角色分组下展示角色

	  	集团授权：普通员工只能查看自己有权限的数据、模块管理员只能查看本组织下的数据、管理组的模块管理员可以查看整个集团数据
	  	数据如何与组织关联？权限数据表的拥有者主表放所属组织并标记数据所属

	  	权限模块的依赖和使用
			1、所有模块均通过这种配置方式来配置模块的权限
			2、在项目启动时，会统一读取模块下的权限配置，加载到内存中
			3、登陆时，查询数据库将用户拥有的权限设置到登陆信息中
			4、访问url时，先跳转到权限控制的拦截器，取出url相关的权限拦截，
				再到用户的权限中去匹配，如果不匹配则不查看，匹配则允许查看
			5、自定义校验器拦截，当为自定义的如数据拦截时，取出参数中传递的数据，然后将数据去匹配可阅读者这些信息，匹配不到则不予以查看
			6、数据列表拦截：根据登陆用户角色如果为管理员、开发者、集团模块管理员则不做任何过滤，如果为模块管理员则根据组织过滤
				如果为自定义权限角色时，在查询条件后拼接sql实现权限控制，对权限数据中模块关键字下，
				所有类型数据有权限人员与当前登录人员去匹配
				注意：匿名用户不做数据权限过滤
			7、开发一套权限控制的标签
	  	依赖关系：登录模块依赖权限、需要权限控制的模块依赖权限、权限依赖（组织用户、基础框架、静态库）
	  	实现工作：
	  		权限模块：解析xml、权限拦截器、数据过滤器、自定义拦截器、权限标签
	  		登陆模块：实现登陆取权限数据写入共用类
	  		基础框架：登陆信息公共类
	  		组织：将登陆用户账号转为登陆用户对象
	  -->

	<table name="msc_auth_info" info="权限信息" status="true">
		<fields>
			<field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
			<field name="描述" id="lb_info" javaType="String" type="varchar" length="255"/>
			<field name="权限代码" id="lb_auth_key" javaType="String" type="varchar" length="200"/>
			<field name="URL前缀" id="lb_url_prefix" javaType="String" type="varchar" length="200"/>
			<field name="所属模块" id="lb_module" javaType="String" type="varchar" length="200"/>
			<field name="所属系统" id="lb_system" javaType="String" type="varchar" length="200"/>
			<field name="模块关键字" id="lb_module_key" javaType="String" type="varchar" length="200"/>
			<field name="系统关键字" id="lb_system_key" javaType="String" type="varchar" length="200"/>
			<field name="更新时间" id="lb_update_time" javaType="Date" />
			<field name="排序号" id="lb_order" javaType="Integer" />
		</fields>
	</table>
    <table name="msc_auth_category" info="角色分组" status="true">
		<fields>
			<field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
			<field name="关键字" id="lb_key" javaType="String" type="varchar" length="200"/>
            <field name="排序号" id="lb_order" javaType="Integer" />
			<field name="备注" id="lb_info" javaType="String" type="varchar" length="255"/>
			<field name="更新时间" id="lb_update_time" javaType="Date" />
		</fields>
	</table>
	<table name="msc_auth_role" info="角色信息" status="true">
		<fields>
			<field name="名称" id="lb_name" javaType="String" type="varchar" length="200"/>
			<field name="关键字" id="lb_key" javaType="String" type="varchar" length="200"/>
			<field name="类型" id="lb_type" javaType="String" type="varchar" length="200"/>
			<field name="是否有效" id="lb_is_valid" javaType="String" type="varchar" length="10"/>
			<field name="备注" id="lb_info" javaType="String" type="varchar" length="255"/>
			<field name="更新时间" id="lb_update_time" javaType="Date" />
			<field
					id="lb_parent"
					name="上级角色"
					javaType="com.bladeray.softdp.msc.auth.domain.MscAuthRole"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
			<field
					id="lb_role_category"
					name="角色分类"
					javaType="com.bladeray.softdp.msc.auth.domain.MscAuthCategory"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
			<field
					id="lb_auth_list"
					name="角色权限"
					javaType="com.bladeray.softdp.msc.auth.domain.MscAuthInfo"
					mapping="ManyToMany"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
			<field
					id="lb_person_list"
					name="角色成员"
					javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
					mapping="ManyToMany"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
		</fields>
	</table>

	<table name="msc_auth_data" info="数据权限" status="true">
		<fields>
			<field name="所属模块" id="lb_module" javaType="String" type="varchar" length="200"/>
			<field name="所属系统" id="lb_system" javaType="String" type="varchar" length="200"/>
			<field name="模块关键字" id="lb_module_key" javaType="String" type="varchar" length="200"/>
			<field name="系统关键字" id="lb_system_key" javaType="String" type="varchar" length="200"/>
			<field name="模块ID" id="lb_model_id" javaType="String" type="varchar" length="200"/>
			<field name="类型" id="lb_type" javaType="String" type="varchar" length="2"/>
			<field name="为空处理" id="lb_null_type" javaType="String" type="varchar" length="2"/>

			<field name="更新时间" id="lb_update_time" javaType="Date" />

			<field
					id="lb_person_list"
					name="角色成员"
					javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
					mapping="ManyToMany"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>

			<field
					id="lb_all_person_list"
					name="角色成员"
					javaType="com.bladeray.softdp.msc.users.domain.MscUsersInfo"
					mapping="ManyToMany"
					foreignId="pkId"
					foreignName="lbName"
					selectType="select"
					dataSource="database"/>
		</fields>
	</table>
</tables>
